<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\en-female-1-neutral.json" LogicalName="LlamaTts.Core.DefaultSpeaker.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.27.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.26.0" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
  </ItemGroup>

</Project>
